version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "14:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wordpress/components"
    versions:
    - 12.0.2
    - 12.0.3
    - 12.0.5
    - 12.0.6
    - 12.0.7
    - 12.0.8
    - 13.0.0
    - 13.0.1
  - dependency-name: "@wordpress/escape-html"
    versions:
    - 1.11.1
    - 1.12.0
    - 1.12.1
  - dependency-name: "@wordpress/api-fetch"
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.5
    - 3.22.0
    - 3.23.0
  - dependency-name: "@wordpress/scripts"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.2
    - 13.0.3
    - 14.0.0
    - 14.0.1
    - 14.1.0
  - dependency-name: "@wordpress/editor"
    versions:
    - 9.25.10
    - 9.25.2
    - 9.25.3
    - 9.25.5
    - 9.25.6
    - 9.25.7
    - 9.25.8
    - 9.25.9
    - 9.26.0
    - 9.26.1
  - dependency-name: "@wordpress/hooks"
    versions:
    - 2.11.1
    - 2.12.0
    - 2.12.1
  - dependency-name: "@wordpress/i18n"
    versions:
    - 3.17.1
    - 3.18.0
    - 3.19.0
    - 3.19.1
  - dependency-name: "@wordpress/element"
    versions:
    - 2.19.1
    - 2.20.0
    - 2.20.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "14:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
