# Tell Travis CI we're using PHP
language: php

dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

install:
  - nvm install
  - npm install
  - composer install

script:
  - npm run lint
