name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - develop
      - "*.*"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: cs2pr

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v3.2.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Node dependencies
        run: npm ci
        env:
          CI: true

      - name: Build Plug-in
        run: npm run build

      - name: Lint
        run: npm run lint
